import type { GitHubIssueItem } from "@/lib/community/collectors/github/github-types";

export const MOCK_GITHUB_ISSUES: GitHubIssueItem[] = [
  {
    id: 101,
    node_id: "MOCK_github_issue_101",
    number: 42,
    title: "Claude Code Opus model unavailable after billing change",
    html_url: "https://github.com/anthropics/claude-code/issues/42",
    repository_url: "https://api.github.com/repos/anthropics/claude-code",
    created_at: "2026-04-26T08:00:00Z",
    updated_at: "2026-04-28T08:30:00Z",
    comments: 18,
    author_association: "MEMBER",
    labels: [{ name: "billing" }, { name: "api" }],
    reactions: { total_count: 7 },
  },
  {
    id: 102,
    node_id: "MOCK_github_issue_102",
    number: 108,
    title: "Document model availability changes for Claude Code",
    html_url: "https://github.com/anthropics/claude-code/issues/108",
    repository_url: "https://api.github.com/repos/anthropics/claude-code",
    created_at: "2026-04-25T03:10:00Z",
    updated_at: "2026-04-27T14:00:00Z",
    comments: 9,
    author_association: "CONTRIBUTOR",
    labels: [{ name: "documentation" }],
    reactions: { total_count: 3 },
  },
  {
    id: 101,
    node_id: "MOCK_github_issue_101",
    number: 42,
    title: "Claude Code Opus model unavailable after billing change",
    html_url: "https://github.com/anthropics/claude-code/issues/42",
    repository_url: "https://api.github.com/repos/anthropics/claude-code",
    created_at: "2026-04-26T08:00:00Z",
    updated_at: "2026-04-28T08:30:00Z",
    comments: 18,
    author_association: "MEMBER",
    labels: [{ name: "billing" }, { name: "api" }],
    reactions: { total_count: 7 },
  },
];
