export type BlogProfileInput = {
  blogName: string;
  targetAudience: string;
  defaultTone: string;
  preferredStructure: string;
  forbiddenPhrases: string;
  seoRules: string;
  htmlRules: string;
  tooltipRules: string;
  imagePromptRules: string;
};

export const refuseHubBlogProfilePreset: BlogProfileInput = {
  blogName: "REFUSE HUB",
  targetAudience: [
    "REFUSE HUB의 주요 독자는 AI 개발 도구, 바이브코딩, Claude Code, Codex, ChatGPT, Gemini CLI, 자동화 도구를 직접 써보며 시행착오를 겪는 초보~중급 개발자, 1인 창작자, 블로그 운영자다.",
    "독자는 이론보다 그래서 실제로 뭘 확인해야 하는지, 어떤 상황에서 어떤 도구를 써야 하는지, 내 환경에서 문제가 생기면 어떻게 판단해야 하는지를 원한다.",
    "글은 전문가 보고서처럼 쓰지 않는다.",
    "실제 사용자가 커뮤니티 떡밥, GitHub 이슈, 공식 문서, 직접 테스트 결과를 보며 판단을 정리하는 느낌으로 쓴다.",
    "출처 없는 경험담은 지어내지 않는다.",
  ].join("\n"),
  defaultTone: [
    "명확하고 실무적인 존댓말을 사용한다.",
    "보고서처럼 딱딱하게 쓰지 말고, 실제 사용자가 자기 블로그에 정리하는 느낌으로 쓴다.",
    "제 기준은 이렇습니다, 저라면 이렇게 봅니다, 아직은 결론을 서두르기보다 이 부분을 먼저 확인하는 편이 낫습니다처럼 개인적인 판단을 자연스럽게 포함한다.",
    "과장, 확정, 홍보성 표현은 피한다.",
    "검수 규칙이나 내부 시스템 규칙을 본문에 그대로 출력하지 않는다.",
    "확인 필요, 단정 불가, 공식 확인 전 같은 표현은 필요할 때만 자연스럽게 풀어쓴다.",
    "영어식 if/then 문장, 개발 계획서식 조건문, 내부 구현 문서 같은 톤은 사용하지 않는다.",
  ].join("\n"),
  preferredStructure: [
    "글은 검색자가 궁금해하는 답부터 시작한다.",
    "",
    "기본 구조:",
    "1. 결론 또는 현재 판단",
    "2. 왜 이 주제가 나왔는지",
    "3. 지금 확인된 것과 아직 확인되지 않은 것",
    "4. 핵심 기준 정리",
    "5. 실제 사용 상황별 예시",
    "6. 체크리스트 또는 판단 기준",
    "7. 개인적인 견해와 마무리",
    "",
    "비교 글 구조:",
    "1. 결론: 언제 A를 쓰고 언제 B를 쓰는가",
    "2. 두 도구 또는 모델의 핵심 차이",
    "3. 작업 유형별 추천 기준",
    "4. 비용, 속도, 실패 비용, 검증 가능성 비교",
    "5. 실제 워크플로우 예시",
    "6. 사용 전 확인할 체크리스트",
    "7. 개인적인 운영 기준으로 마무리",
    "",
    "커뮤니티 떡밥/루머 글 구조:",
    "1. 커뮤니티에서 어떤 이야기가 나왔는지",
    "2. 왜 사람들이 반응하는지",
    "3. GitHub Issues, 공식 문서, 뉴스 등 보강 신호가 있는지",
    "4. 아직 공식 확인이 안 된 부분",
    "5. 내가 보기엔 무엇을 조심해야 하는지",
    "6. 지금 할 수 있는 현실적인 확인 방법",
    "7. 개인적인 판단으로 마무리",
    "",
    "본문에 내부 구현 설명을 끼워 넣지 않는다.",
    "WriterService, GenerationLog, approval guard, API route, provider, fallback 같은 내부 용어는 글 주제가 REFUSE HUB 개발기일 때만 사용한다.",
    "일반 독자용 글에서는 검수 규칙보다 판단 기준을 보여준다.",
  ].join("\n"),
  forbiddenPhrases: [
    "무조건, 100% 보장, 클릭만 하면, 완전 자동화, 생산성이 폭발한다, 운영이 완전히 자동화된다 같은 과장 표현을 피한다.",
    "정책, 가격, API 기능, 보안, 최신 트렌드는 공식 확인 없이 단정하지 않는다.",
    "",
    "아래 표현은 일반 본문에 그대로 쓰지 않는다.",
    "- 현재 입력 기준으로 공식 확인된 자료는 없습니다",
    "- 공식 자료를 근거로 단정할 수는 없습니다",
    "- 모두 확인 필요로 두는 것이 안전합니다",
    "- 확인 필요 항목입니다",
    "- if ... then ...",
    "- WriterService",
    "- GenerationLog",
    "- approval guard",
    "- provider success E2E",
    "- API route",
    "- DB model",
    "- oauth-proxy",
    "- OpenAI-compatible provider",
    "- Tistory Export",
    "- TrendCandidate",
    "- sourceMetaJson",
    "- needs_manual_review",
    "- official_confirmed",
    "",
    "단, REFUSE HUB 개발기나 프로젝트 구현 설명 글에서는 내부 구현 용어를 사용할 수 있다.",
    "출처 없는 사용자 의견을 지어내지 않는다.",
    "사람들이 다 그렇게 말한다, 대부분의 사용자가 불만이다처럼 근거 없는 일반화도 피한다.",
  ].join("\n"),
  seoRules: [
    "핵심 키워드 1개를 제목 앞부분에 자연스럽게 포함한다.",
    "태그는 8~10개를 권장한다.",
    "검색자가 실제로 입력할 만한 표현을 우선한다.",
    "",
    "비교 글 태그 예:",
    "Claude Code, Claude Opus, Claude Sonnet, Opus Sonnet 차이, Claude Code 모델 선택, AI 코딩 도구, 코딩 에이전트, 모델 선택 기준, Anthropic",
    "",
    "커뮤니티 떡밥 글 태그 예:",
    "Claude Code, Claude Pro, Claude Opus, Opus 제공 중단설, Claude Code 이슈, AI 코딩 도구, Anthropic, 개발자 요금제, 모델 제공 정책, AI 도구 루머",
    "",
    "피할 태그:",
    "WriterService, GenerationLog, approval guard, oauth-proxy, API Route, provider success E2E, Tistory Export, 내부 테스트명, 너무 넓은 AI/자동화/SEO 단독 태그",
    "",
    "metaDescription은 120~150자 안팎으로 작성한다.",
    "본문에는 metaDescription과 태그를 섞지 않는다.",
  ].join("\n"),
  htmlRules: [
    "REFUSE HUB의 티스토리 HTML 편집기에 바로 붙여넣을 수 있는 본문 HTML을 우선한다.",
    '일반 문단은 <p data-ke-size="size16">...</p> 형식을 사용한다.',
    'H2는 <h2 data-ke-size="size26">...</h2> 형식을 사용한다.',
    "리스트는 티스토리 호환 형식을 사용한다.",
    "표는 필요한 경우에만 사용하고, 모바일에서 너무 복잡하지 않게 만든다.",
    "본문 HTML에는 제목, 메타 설명, 태그, 검수 리포트를 섞지 않는다.",
    "본문 HTML에는 script, iframe, onerror, javascript: URL, inline event handler를 넣지 않는다.",
    "HTML 태그가 &lt;p&gt;처럼 escaped 문자열로 보이지 않게 한다.",
    "코드블록은 실제 코드 설명이 필요한 글에서만 사용한다.",
    "일반 비교/루머/의견 글에서는 코드블록을 남발하지 않는다.",
  ].join("\n"),
  tooltipRules: [
    "낯선 약어, 개발 용어, AI 도구명, 인증 방식, API 용어는 첫 등장 시 짧은 설명을 붙인다.",
    "단, 설명이 본문 흐름을 끊지 않게 한다.",
    "용어 설명은 1문장 이내로 짧게 쓴다.",
    "내부 구현 용어는 일반 글에서는 되도록 쓰지 않는다.",
    "꼭 필요하면 독자용 표현으로 먼저 풀어쓴다.",
  ].join("\n"),
  imagePromptRules: [
    "REFUSE HUB의 이미지는 실제 작업 맥락을 반영한 스크린샷형 또는 다이어그램형 이미지를 우선한다.",
    "과장된 미래형 AI 이미지, 네온 회로, 홀로그램, 의미 없는 로봇 이미지는 피한다.",
    "",
    "AI 개발 도구 글에서는 다음 방향을 우선한다.",
    "- 개발자가 여러 AI 코딩 도구를 비교하는 작업 화면",
    "- 모델 선택 체크리스트가 있는 노트와 코드 에디터",
    "- 커뮤니티 신호 -> GitHub 이슈 -> 공식 문서 확인으로 이어지는 흐름 다이어그램",
    "- 티스토리 블로그 초안 검수 화면 느낌",
    "",
    "이미지에는 로고, 브랜드명, 읽을 수 있는 가짜 텍스트, 실제 인물 얼굴을 넣지 않는다.",
  ].join("\n"),
};

export const defaultBlogProfileInput = refuseHubBlogProfilePreset;
